server:
  applicationConnectors:
  - type: http
  adminConnectors:
  - type: http
logging:
  level: INFO
  loggers:
    org.metadatacenter: DEBUG
    org.metadatacenter.server.neo4j.proxy.AbstractNeo4JProxy: INFO
    o.m.s.neo4j.proxy.AbstractNeo4JProxy: INFO
    org.metadatacenter.server.search.elasticsearch: INFO
    org.metadatacenter.server.search.permission: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ${CEDAR_HOME}/log/cedar-worker-server/dropwizard.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ${CEDAR_HOME}/log/cedar-worker-server/dropwizard-%d.log
      archivedFileCount: 5
      timeZone: UTC
